version: '3.8'

services:
  wtma-landing:
    build: .
    container_name: wtma-landing-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8082:80"
    networks:
      - wtma
    environment:
      - TZ=Asia/Tashkent

networks:
  wtma:
    external: true
