# /etc/nginx/sites-available/landing.okaposai.uz
# Serveringizdagi asosiy Nginx konfiguratsiyasi

server {
    listen 80;
    server_name landing.okaposai.uz;

    # Katta fayllar yoki so'rovlar uchun limit
    client_max_body_size 20M;

    location / {
        # Docker konteyneri tashqi portiga yo'naltirish (docker-compose dagi 8088 port)
        proxy_pass http://127.0.0.1:8088;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Timeoutlar
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
